// Generated by Fabrica dev
// Template: init/go.mod.tmpl
// Generated: 2026-05-01T10:13:12-07:00

module github.com/user/bmc-manager

go 1.26.2

require (
	github.com/go-chi/chi/v5 v5.0.10
	github.com/openchami/fabrica v0.4.1
	github.com/spf13/cobra v1.10.2
	github.com/spf13/viper v1.16.0
	gopkg.in/yaml.v3 v3.0.1
)

require (
	entgo.io/ent v0.14.6 // indirect
	golang.org/x/text v0.36.0 // indirect
)
