// Code generated by Fabrica dev. DO NOT EDIT.
// Template: server/handlers.go.tmpl
// Generated: 2026-05-01T17:24:30Z
//
// # Copyright © 2026 OpenCHAMI a Series of LF Projects, LLC
//
// SPDX-License-Identifier: MIT
//
// This file contains REST API handlers for BmcCredential resources.
//
// To modify this code:
//  1. Edit the template file: pkg/codegen/templates/handlers.go.tmpl
//  2. Run 'fabrica generate' to regenerate
//  3. Do NOT edit this file directly - changes will be lost
//
// Generated handlers provide:
//   - GET /bmccredentials (list all bmccredentials)
//   - GET /bmccredentials/{uid} (get specific BmcCredential)
//   - POST /bmccredentials (create new BmcCredential)
//   - PUT /bmccredentials/{uid} (update BmcCredential spec)
//   - PATCH /bmccredentials/{uid} (patch BmcCredential spec)
//   - DELETE /bmccredentials/{uid} (delete BmcCredential)
//   - PUT /bmccredentials/{uid}/status (update BmcCredential status)
//   - PATCH /bmccredentials/{uid}/status (patch BmcCredential status)
//
// Authorization: Add custom middleware for authentication/authorization
// Storage: Uses storage.LoadBmcCredential*/SaveBmcCredential*/DeleteBmcCredential*
// Version Support: Available (see version context in handlers)
//
// To enable full version conversion for this resource:
//  1. Add new version: fabrica add version <group> <version>
//  2. Implement converter: apis/<group>/<version>/converter.go
//  3. Add version-aware storage: storage.LoadBmcCredentialWithVersion()
//  4. Register versions in cmd/server/main.go
package main

import (
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"time"

	"github.com/go-chi/chi/v5"
	"github.com/openchami/fabrica/pkg/events"
	"github.com/openchami/fabrica/pkg/patch"
	"github.com/openchami/fabrica/pkg/resource"
	"github.com/openchami/fabrica/pkg/validation"
	"github.com/openchami/fabrica/pkg/versioning"
	v1 "github.com/user/bmc-manager/apis/example.fabrica.dev/v1"

	"github.com/user/bmc-manager/internal/storage"
)

// GetBmcCredentials returns all BmcCredential resources
func GetBmcCredentials(w http.ResponseWriter, r *http.Request) {
	// Authorization: Add custom middleware in routes.go or implement checks here
	// Example: if !authorized(r) { respondError(w, http.StatusUnauthorized, fmt.Errorf("unauthorized")); return }

	bmccredentials, err := storage.LoadAllBmcCredentials(r.Context())
	if err != nil {
		respondError(w, http.StatusInternalServerError, fmt.Errorf("failed to load bmccredentials: %w", err))
		return
	}
	respondJSON(w, http.StatusOK, bmccredentials)
}

// GetBmcCredential returns a specific BmcCredential resource by UID
func GetBmcCredential(w http.ResponseWriter, r *http.Request) {
	uid := chi.URLParam(r, "uid")
	if uid == "" {
		respondError(w, http.StatusBadRequest, fmt.Errorf("BmcCredential UID is required"))
		return
	}

	// Version context available here for version-aware operations
	// versionCtx := versioning.GetVersionContext(r.Context())
	// Requested version: versionCtx.ServeVersion
	// To enable: replace storage.LoadBmcCredential() with version-aware function

	// Authorization: Add custom middleware in routes.go or implement checks here
	// Example: if !authorized(r) { respondError(w, http.StatusUnauthorized, fmt.Errorf("unauthorized")); return }

	bmcCredential, err := storage.LoadBmcCredential(r.Context(), uid)
	if err != nil {
		respondError(w, http.StatusNotFound, fmt.Errorf("BmcCredential not found: %w", err))
		return
	}
	respondJSON(w, http.StatusOK, bmcCredential)
}

// CreateBmcCredential creates a new BmcCredential resource
func CreateBmcCredential(w http.ResponseWriter, r *http.Request) {
	var req CreateBmcCredentialRequest
	if err := json.NewDecoder(r.Body).Decode(&req); err != nil {
		respondError(w, http.StatusBadRequest, fmt.Errorf("invalid request body: %w", err))
		return
	}

	// Layer 1: Request validation (validates inline spec fields and metadata)
	if err := validation.ValidateResource(&req); err != nil {
		respondError(w, http.StatusBadRequest, fmt.Errorf("validation failed: %w", err))
		return
	}

	// Get version context from request (set by version negotiation middleware)
	versionCtx := versioning.GetVersionContext(r.Context())

	uid, err := resource.GenerateUIDForResource("BmcCredential")
	if err != nil {
		respondError(w, http.StatusInternalServerError, fmt.Errorf("failed to generate UID: %w", err))
		return
	}

	// Versioned mode: flat fields with fabrica.Metadata
	bmcCredential := &v1.BmcCredential{
		// Use negotiated ServeVersion (from Accept header) for apiVersion
		APIVersion: versionCtx.ServeVersion,
		Kind:       "BmcCredential",
		Spec:       req.AsSpec(),
	}

	// Initialize metadata from request
	bmcCredential.Metadata = req.Metadata
	bmcCredential.Metadata.UID = uid
	now := time.Now()
	bmcCredential.Metadata.CreatedAt = now
	bmcCredential.Metadata.UpdatedAt = now

	// Set labels and annotations
	if bmcCredential.Metadata.Labels == nil {
		bmcCredential.Metadata.Labels = make(map[string]string)
	}
	for k, v := range req.Labels {
		bmcCredential.Metadata.Labels[k] = v
	}
	if bmcCredential.Metadata.Annotations == nil {
		bmcCredential.Metadata.Annotations = make(map[string]string)
	}
	for k, v := range req.Annotations {
		bmcCredential.Metadata.Annotations[k] = v
	}

	// Layer 2: Custom business logic validation
	if err := validation.ValidateWithContext(r.Context(), bmcCredential); err != nil {
		respondError(w, http.StatusBadRequest, fmt.Errorf("validation failed: %w", err))
		return
	}

	// Set initial status
	// This assumes the generator passes an 'IsReconcilable' boolean
	// to this template, and that the resource has a .Status.Phase field.

	// Save (Layer 1: Ent validation happens automatically if using Ent storage)
	if err := storage.SaveBmcCredential(r.Context(), bmcCredential); err != nil {
		respondError(w, http.StatusInternalServerError, fmt.Errorf("failed to save BmcCredential: %w", err))
		return
	}

	// Publish resource created event

	if err := events.PublishResourceCreated(r.Context(), "BmcCredential", bmcCredential.Metadata.UID, bmcCredential.Metadata.Name, bmcCredential); err != nil {
		// Log the error but don't fail the request - events are non-critical
		fmt.Printf("Warning: Failed to publish resource created event for BmcCredential %s: %v\n", bmcCredential.Metadata.UID, err)

	}

	respondJSON(w, http.StatusCreated, bmcCredential)
}

// UpdateBmcCredential updates the spec of an existing BmcCredential resource
// NOTE: This endpoint ONLY updates the spec. Use PUT //bmccredentials/{uid}/status to update status.
func UpdateBmcCredential(w http.ResponseWriter, r *http.Request) {
	uid := chi.URLParam(r, "uid")
	if uid == "" {
		respondError(w, http.StatusBadRequest, fmt.Errorf("BmcCredential UID is required"))
		return
	}

	bmcCredential, err := storage.LoadBmcCredential(r.Context(), uid)
	if err != nil {
		respondError(w, http.StatusNotFound, fmt.Errorf("BmcCredential not found: %w", err))
		return
	}

	var req UpdateBmcCredentialRequest
	if err := json.NewDecoder(r.Body).Decode(&req); err != nil {
		respondError(w, http.StatusBadRequest, fmt.Errorf("invalid request body: %w", err))
		return
	}

	// Apply updates

	// Versioned mode: direct field access
	if req.Metadata.Name != "" {
		bmcCredential.Metadata.Name = req.Metadata.Name
	}

	// Update spec fields ONLY - status should use /status subresource
	bmcCredential.Spec = req.AsSpec()

	// Update labels and annotations
	if bmcCredential.Metadata.Labels == nil {
		bmcCredential.Metadata.Labels = make(map[string]string)
	}
	for k, v := range req.Labels {
		bmcCredential.Metadata.Labels[k] = v
	}
	if bmcCredential.Metadata.Annotations == nil {
		bmcCredential.Metadata.Annotations = make(map[string]string)
	}
	for k, v := range req.Annotations {
		bmcCredential.Metadata.Annotations[k] = v
	}

	// Update timestamp
	bmcCredential.Metadata.UpdatedAt = time.Now()

	if err := storage.SaveBmcCredential(r.Context(), bmcCredential); err != nil {
		respondError(w, http.StatusInternalServerError, fmt.Errorf("failed to save BmcCredential: %w", err))
		return
	}

	// Publish resource updated event
	updateMetadata := map[string]interface{}{
		"updatedAt": bmcCredential.Metadata.UpdatedAt,
	}

	if err := events.PublishResourceUpdated(r.Context(), "BmcCredential", bmcCredential.Metadata.UID, bmcCredential.Metadata.Name, bmcCredential, updateMetadata); err != nil {
		// Log the error but don't fail the request - events are non-critical
		fmt.Printf("Warning: Failed to publish resource updated event for BmcCredential %s: %v\n", bmcCredential.Metadata.UID, err)

	}

	respondJSON(w, http.StatusOK, bmcCredential)
}

// PatchBmcCredential patches an existing BmcCredential resource spec using JSON Merge Patch, JSON Patch, or Shorthand Patch
// Only the spec portion of the resource can be patched - metadata and status are API-managed
func PatchBmcCredential(w http.ResponseWriter, r *http.Request) {
	uid := chi.URLParam(r, "uid")
	if uid == "" {
		respondError(w, http.StatusBadRequest, fmt.Errorf("BmcCredential UID is required"))
		return
	}

	bmcCredential, err := storage.LoadBmcCredential(r.Context(), uid)
	if err != nil {
		respondError(w, http.StatusNotFound, fmt.Errorf("BmcCredential not found: %w", err))
		return
	}

	// Read patch document
	patchData, err := io.ReadAll(r.Body)
	if err != nil {
		respondError(w, http.StatusBadRequest, fmt.Errorf("failed to read patch data: %w", err))
		return
	}

	// Marshal current spec to JSON for patching (only allow spec modifications)
	currentSpecJSON, err := json.Marshal(bmcCredential.Spec)
	if err != nil {
		respondError(w, http.StatusInternalServerError, fmt.Errorf("failed to marshal current spec: %w", err))
		return
	}

	// Detect patch type from Content-Type header
	contentType := r.Header.Get("Content-Type")
	patchType := patch.DetectPatchType(contentType)

	// Apply patch to spec only
	patchResult, err := patch.ApplyPatchWithOptions(currentSpecJSON, patchData, patchType, patch.PatchOptions{
		AllowAddFields:    true,
		AllowRemoveFields: true,
	})
	if err != nil {
		respondError(w, http.StatusUnprocessableEntity, fmt.Errorf("failed to apply patch to spec: %w", err))
		return
	}

	// Unmarshal the patched result back to the spec
	if err := json.Unmarshal(patchResult.Updated, &bmcCredential.Spec); err != nil {
		respondError(w, http.StatusInternalServerError, fmt.Errorf("failed to unmarshal patched spec: %w", err))
		return
	}

	// Touch to update metadata

	bmcCredential.Metadata.UpdatedAt = time.Now()

	// Save the patched resource
	if err := storage.SaveBmcCredential(r.Context(), bmcCredential); err != nil {
		respondError(w, http.StatusInternalServerError, fmt.Errorf("failed to save patched BmcCredential: %w", err))
		return
	}

	// Publish resource patched event
	patchMetadata := map[string]interface{}{
		"patchType": patchType,
		"updatedAt": bmcCredential.Metadata.UpdatedAt,
	}

	if err := events.PublishResourcePatched(r.Context(), "BmcCredential", bmcCredential.Metadata.UID, bmcCredential.Metadata.Name, bmcCredential, patchMetadata); err != nil {
		// Log the error but don't fail the request - events are non-critical
		fmt.Printf("Warning: Failed to publish resource patched event for BmcCredential %s: %v\n", bmcCredential.Metadata.UID, err)

	}

	respondJSON(w, http.StatusOK, bmcCredential)
}

// UpdateBmcCredentialStatus updates only the status of a BmcCredential resource
// This endpoint is intended for controllers, reconcilers, and monitoring systems.
// It does not modify the spec or metadata (except updatedAt timestamp).
//
// Authorization: Requires 'update_status' permission (separate from 'update' permission)
// Events: Publishes resource updated event with updateType: "status"
func UpdateBmcCredentialStatus(w http.ResponseWriter, r *http.Request) {
	uid := chi.URLParam(r, "uid")
	if uid == "" {
		respondError(w, http.StatusBadRequest, fmt.Errorf("BmcCredential UID is required"))
		return
	}

	// Authorization: Add custom middleware for status update authorization
	// Status updates can have different permissions than spec updates

	res, err := storage.LoadBmcCredential(r.Context(), uid)
	if err != nil {
		respondError(w, http.StatusNotFound, fmt.Errorf("BmcCredential not found: %w", err))
		return
	}

	var statusUpdate v1.BmcCredentialStatus
	if err := json.NewDecoder(r.Body).Decode(&statusUpdate); err != nil {
		respondError(w, http.StatusBadRequest, fmt.Errorf("invalid status body: %w", err))
		return
	}

	// Preserve spec - only update status
	res.Status = statusUpdate

	res.Metadata.UpdatedAt = time.Now()

	if err := storage.SaveBmcCredential(r.Context(), res); err != nil {
		respondError(w, http.StatusInternalServerError, fmt.Errorf("failed to save BmcCredential status: %w", err))
		return
	}

	// Publish status update event
	statusMetadata := map[string]interface{}{
		"updatedAt":  res.Metadata.UpdatedAt,
		"updateType": "status",
	}

	if err := events.PublishResourceUpdated(r.Context(), "BmcCredential", res.Metadata.UID, res.Metadata.Name, res, statusMetadata); err != nil {
		// Log but don't fail - events are non-critical
		fmt.Printf("Warning: Failed to publish status update event for BmcCredential %s: %v\n", res.Metadata.UID, err)

	}

	respondJSON(w, http.StatusOK, res)
}

// PatchBmcCredentialStatus patches only the status of a BmcCredential resource
// Supports JSON Merge Patch, JSON Patch, and Shorthand Patch formats.
// Only modifies status fields - spec and metadata are preserved.
func PatchBmcCredentialStatus(w http.ResponseWriter, r *http.Request) {
	uid := chi.URLParam(r, "uid")
	if uid == "" {
		respondError(w, http.StatusBadRequest, fmt.Errorf("BmcCredential UID is required"))
		return
	}

	// Authorization: Add custom middleware for status patch authorization
	// Status patches can have different permissions than spec patches

	res, err := storage.LoadBmcCredential(r.Context(), uid)
	if err != nil {
		respondError(w, http.StatusNotFound, fmt.Errorf("BmcCredential not found: %w", err))
		return
	}

	patchData, err := io.ReadAll(r.Body)
	if err != nil {
		respondError(w, http.StatusBadRequest, fmt.Errorf("failed to read patch data: %w", err))
		return
	}

	// Marshal current status for patching
	currentStatusJSON, err := json.Marshal(res.Status)
	if err != nil {
		respondError(w, http.StatusInternalServerError, fmt.Errorf("failed to marshal current status: %w", err))
		return
	}

	contentType := r.Header.Get("Content-Type")
	patchType := patch.DetectPatchType(contentType)

	patchResult, err := patch.ApplyPatchWithOptions(currentStatusJSON, patchData, patchType, patch.PatchOptions{
		AllowAddFields:    true,
		AllowRemoveFields: false, // Don't allow removing status fields
	})
	if err != nil {
		respondError(w, http.StatusUnprocessableEntity, fmt.Errorf("failed to apply patch to status: %w", err))
		return
	}

	// Unmarshal patched status back
	if err := json.Unmarshal(patchResult.Updated, &res.Status); err != nil {
		respondError(w, http.StatusInternalServerError, fmt.Errorf("failed to unmarshal patched status: %w", err))
		return
	}

	res.Metadata.UpdatedAt = time.Now()

	if err := storage.SaveBmcCredential(r.Context(), res); err != nil {
		respondError(w, http.StatusInternalServerError, fmt.Errorf("failed to save patched BmcCredential status: %w", err))
		return
	}

	// Publish status patch event
	patchMetadata := map[string]interface{}{
		"patchType":  patchType,
		"updatedAt":  res.Metadata.UpdatedAt,
		"updateType": "status",
	}

	if err := events.PublishResourcePatched(r.Context(), "BmcCredential", res.Metadata.UID, res.Metadata.Name, res, patchMetadata); err != nil {
		fmt.Printf("Warning: Failed to publish status patch event for BmcCredential %s: %v\n", res.Metadata.UID, err)

	}

	respondJSON(w, http.StatusOK, res)
}

// DeleteBmcCredential deletes a BmcCredential resource
func DeleteBmcCredential(w http.ResponseWriter, r *http.Request) {
	uid := chi.URLParam(r, "uid")
	if uid == "" {
		respondError(w, http.StatusBadRequest, fmt.Errorf("BmcCredential UID is required"))
		return
	}

	// Load resource before deletion for event publishing
	bmcCredential, err := storage.LoadBmcCredential(r.Context(), uid)
	if err != nil {
		respondError(w, http.StatusNotFound, fmt.Errorf("BmcCredential not found: %w", err))
		return
	}

	if err := storage.DeleteBmcCredential(r.Context(), uid); err != nil {
		respondError(w, http.StatusInternalServerError, fmt.Errorf("failed to delete BmcCredential: %w", err))
		return
	}

	// Publish resource deleted event
	deleteMetadata := map[string]interface{}{
		"deletedAt": time.Now(),
	}

	if err := events.PublishResourceDeleted(r.Context(), "BmcCredential", bmcCredential.Metadata.UID, bmcCredential.Metadata.Name, deleteMetadata); err != nil {
		// Log the error but don't fail the request - events are non-critical
		fmt.Printf("Warning: Failed to publish resource deleted event for BmcCredential %s: %v\n", bmcCredential.Metadata.UID, err)

	}

	respondJSON(w, http.StatusOK, &DeleteResponse{
		Message: "BmcCredential deleted successfully",
		UID:     uid,
	})
}
